services:
  - type: web
    name: hackapp
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: oregon
    envVars:
      - key: JAVA_HOME
        value: "/usr/lib/jvm/java-17-openjdk"
    healthCheckPath: /
