services:
  - type: web
    name: hackapp
    env: java
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/hackapp-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_HOME
        value: "/usr/lib/jvm/java-17"
