name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    services:
      app:
        image: hackapp
        ports:
          - 8080:8080
        options: > 
          --network zap-network

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run app in Docker
        run: |
          docker build -t hackapp .
          docker run -d --network zap-network -p 8080:8080 hackapp

      - name: Run OWASP ZAP
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://app:8080'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
