name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  build_and_zap:
    runs-on: ubuntu-latest
    services:
      app:
        image: hackapp:latest
        ports:
          - 8080:8080
        options: --health-cmd="curl --fail http://localhost:8080 || exit 1" --health-interval=10s --health-retries=5 --health-timeout=5s
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t hackapp .

      - name: Wait for Application to be Ready
        run: |
          while ! curl -s http://localhost:8080; do
            echo "Waiting for app to be ready..."
            sleep 10
          done

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-a'
