name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP ZAP
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          target: 'http://localhost:8080'
