name: OWASP ZAP Scan

on:
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run OWASP ZAP
        uses: zaproxy/action-full-scan@v0.4.1
        with:
          target: 'http://localhost:8080'
