name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build and run the application using Dockerfile
      - name: Build the Docker image
        run: |
          docker build -t my-app .

      - name: Run the application container
        run: |
          docker run -d -p 8080:8080 my-app

      # Wait for the application to be ready
      - name: Wait for the application to be ready
        run: |
          until curl -s http://localhost:8080; do
            echo "Waiting for application..."
            sleep 10
          done

      # Run OWASP ZAP Full Scan
      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:8080'
          cmd_options: '-a'
          rules_file_name: '.zap/rules.tsv'
